### ISSUE TITLE
Last "page" missing

### ISSUE THREAD

**Issue by luispy87** [ariten/Monday-to-PowerBi#1]
Hi my friend, 

I've tried your code, it's working fine but for some reason, the las't table is not recognized and is not loading all the date set. Please let me know if is possible to solve the issue.

Example

The monday boards have 1752 items,

GetFirst is configure with items page (limit: 500)
GetNext also next_items_page(limit:500

the end result is a 1500 rows data set, 
if I configure the next_items_pag(limit100, the results is a table with 1700 items, 52 rows missing
if I configure the next_items_pag(limit10, the results is a table with 1750 items, 2 rows missing

so the last "page" for some reason is missing

Please let me know if there is solution

**Comment by tomiapo** [comment]
Hi @luispy87 , I have created a copy of this repo and updated it to solve the issue you mention. You can find it here: https://github.com/tomiapo/monday-to-powerbi

@ariten the issue is related to the List.Generate function. Since the cursor equals **_null_** in the last page, it does not take into account the records from that page. I have updated it to make an additional fetch using the **_null_** cursor (returning an error on purpose) and using that error as a stop condition (I had to update the GetNext function as well for it to handle the **_null_** cursor properly).

**Comment by luispy87** [comment]
Great @tomiapo!!! Thanks a lot!

**Comment by ariten** [comment]
Thanks for raising this @luispy87 , i am not very active on GitHub so missed this being posted. 

Thank you to @tomiapo for posting a solution, i have verified the bug and it is in this version of my solution and the fix posted does work!

**Comment by ariten** [comment]
Issue has now been closed and the repo has been updated to reflect the solution, credit has been given to @tomiapo for your solution in the readme. Thanks both for raising and fixing this bug
